Repository wecode-bootcamp-korea/37-backend-westagram, pull requests merged in 2022-09, with the labels that each got.

#4 [장기석-TeamA] Assignment 2 : Express API - 유저 회원가입 하기
  teamA/gisuk/.env.sample
  teamA/gisuk/app.js
Labels: 멘토 리뷰 요청

#7 [조경찬-teamB] Assingment 1: Express API - 초기 환경 세팅
  teamB/kyoungchanCho/.env.sample
  teamB/kyoungchanCho/.gitignore
  teamB/kyoungchanCho/app.js
  teamB/kyoungchanCho/package-lock.json
  teamB/kyoungchanCho/package.json
Labels: 완료

#28 [정다영-teamC] Assignment 1: Express API - 초기 환경 세팅
  teamC/dayoung/.env.sample
  teamC/dayoung/.gitignore
  teamC/dayoung/app.js
  teamC/dayoung/db/migrations/20220901074600_users.sql
  teamC/dayoung/db/migrations/20220901074711_posts.sql
  teamC/dayoung/db/migrations/20220901074718_likes.sql
  teamC/dayoung/db/migrations/20220901074740_comments.sql
  teamC/dayoung/package-lock.json
  teamC/dayoung/package.json
Labels: 멘토 리뷰 요청

#16 [정우진-teamb] Assignment 1: Express API - 초기 환경 세팅
  teamB/JeongWooJin/.env.sample
  teamB/JeongWooJin/.gitignore
  teamB/JeongWooJin/app.js
  teamB/JeongWooJin/db/migrations/20220831015902_create_users_table.sql
  teamB/JeongWooJin/db/migrations/20220831015911_create_posts_table.sql
  teamB/JeongWooJin/db/migrations/20220831015918_create_likes_table.sql
  teamB/JeongWooJin/package-lock.json
  teamB/JeongWooJin/package.json
Labels: 완료

#18 [김응수-TeamB] Assignment 1 : Express API - Express 초기 환경 세팅
  teamB/eungSooKim/.env.sample
  teamB/eungSooKim/.gitignore
  teamB/eungSooKim/app.js
  teamB/eungSooKim/db/migrations/20220831110804_users.sql
  teamB/eungSooKim/db/migrations/20220831111048_posts.sql
  teamB/eungSooKim/db/migrations/20220831111054_likes.sql
  teamB/eungSooKim/db/migrations/20220831111107_comments.sql
  teamB/eungSooKim/package-lock.json
  teamB/eungSooKim/package.json
Labels: 완료

#23 [정윤아-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/jeongyunah/.gitignore
  teamB/jeongyunah/app.js
  teamB/jeongyunah/db/migrations/20220830111337_users.sql
  teamB/jeongyunah/package-lock.json
  teamB/jeongyunah/package.json
Labels: 완료

#38 [김성식-teamC] Assignment 1: Express API - 초기 환경 세팅
  teamC/sungsik/.env.sample
  teamC/sungsik/.gitignore
  teamC/sungsik/app.js
  teamC/sungsik/db/migrations/20220902043124_users.sql
  teamC/sungsik/db/migrations/20220902043128_posts.sql
  teamC/sungsik/db/migrations/20220902043133_comments.sql
  teamC/sungsik/db/migrations/20220902043153_likes.sql
  teamC/sungsik/db/schema.sql
  teamC/sungsik/package-lock.json
  teamC/sungsik/package.json
Labels: 멘토 리뷰 요청

#39 [김성식-teamC] Assignment 2: Express API - 유저 회원가입 하기
  teamC/sungsik/app.js
Labels: 멘토 리뷰 요청

#21 [허신애-teamC] Assignment 1: Express API - 초기 환경 설정
  teamC/shinae/.env.sample
  teamC/shinae/.gitignore
  teamC/shinae/app.js
  teamC/shinae/db/migrations/20220902124457_create_users_table.sql
  teamC/shinae/db/migrations/20220902124503_create_posts_table.sql
  teamC/shinae/db/migrations/20220902124512_create_likes_table.sql
  teamC/shinae/db/migrations/20220902124518_create_comment_table.sql
  teamC/shinae/package-lock.json
  teamC/shinae/package.json
Labels: 멘토 리뷰 요청

#29 [정다영-teamC] Assignment 2: Express API - 유저 회원가입 하기
  teamC/dayoung/app.js
Labels: 멘토 리뷰 요청

#19 [장기석-teamA] Assignment 3 : Express API - CRUD
  teamA/gisuk/app.js
Labels: 멘토 리뷰 요청

#26 [최진우-teamA]Assignment 1 : Express API - 초기 환경 세팅
  teamA/jinwoo/.env.sample
  teamA/jinwoo/.gitignore
  teamA/jinwoo/app.js
  teamA/jinwoo/db/migrations/20220831030717_create_westagram_users_table.sql
  teamA/jinwoo/db/migrations/20220831070358_create_westagram_posts_table.sql
  teamA/jinwoo/db/migrations/20220831070412_create_westagram_likes_table.sql
  teamA/jinwoo/db/migrations/20220831081914_create_westagram_comments_table.sql
  teamA/jinwoo/package-lock.json
  teamA/jinwoo/package.json
Labels: 멘토 리뷰 요청

#30 [정다영-teamC] Assignment 3 : Express API - CRUD
  teamC/dayoung/app.js
  teamC/dayoung/db/migrations/20220901074718_likes.sql
  teamC/dayoung/db/migrations/20220902124818_likes_addUnique.sql
Labels: 멘토 리뷰 요청

#49 [허신애-teamC] Assignment 2: Express API - 유저 회원가입 하기
  teamC/shinae/.env.sample
  teamC/shinae/app.js
Labels: 멘토 리뷰 요청

#20 [김응수-TeamB] Assignment 2 : Express API - 유저 회원가입 하기
  teamB/eungSooKim/app.js
  teamB/eungSooKim/db/migrations/20220831110804_create_users.sql
  teamB/eungSooKim/db/migrations/20220831111048_create_posts.sql
  teamB/eungSooKim/db/migrations/20220831111054_create_likes.sql
  teamB/eungSooKim/db/migrations/20220831111107_create_comments.sql
  teamB/eungSooKim/db/migrations/20220903070640_modify_likes.sql
Labels: 멘토 리뷰 요청

#42 [정윤아-teamB] Assignment 2: Express API - 유저 회원가입 하기
  teamB/jeongyunah/app.js
  teamB/jeongyunah/db/migrations/20220830111337_create_users.sql
  teamB/jeongyunah/db/migrations/20220830111337_users.sql
  teamB/jeongyunah/db/migrations/20220902040733_create_posts.sql
  teamB/jeongyunah/db/migrations/20220902040801_create_likes.sql
  teamB/jeongyunah/db/migrations/20220902040811_create_comments.sql
  teamB/jeongyunah/db/migrations/20220904063046_modify_likes_table.sql
Labels: 멘토 리뷰 요청

#51 [조경찬-teamB] Assignment 2: Express API - 유저 회원가입 하기
  teamB/kyoungchanCho/app.js
  teamB/kyoungchanCho/db/migrations/20220901070751_create_users_table.sql
  teamB/kyoungchanCho/db/migrations/20220901070759_create_posts_table.sql
  teamB/kyoungchanCho/db/migrations/20220901070806_create_likes_table.sql
Labels: 멘토 리뷰 요청

#14 [조준형-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/junhyungcho/.gitignore
  teamB/junhyungcho/app.js
  teamB/junhyungcho/package-lock.json
  teamB/junhyungcho/package.json
Labels: 완료

#44 [김정훈-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/jeonghun/.gitignore
  teamB/jeonghun/app.js
  teamB/jeonghun/db/migrations/20220903113020_create_users_table.sql
  teamB/jeonghun/db/migrations/20220903113033_create_posts_table.sql
  teamB/jeonghun/db/migrations/20220903113043_create_likes_table.sql
  teamB/jeonghun/package-lock.json
  teamB/jeonghun/package.json
Labels: 멘토 리뷰 요청

#53 [김성식-teamC] Assignment 3: Express API - CRUD
  teamC/sungsik/app.js
  teamC/sungsik/db/migrations/20220902043128_posts.sql
  teamC/sungsik/db/schema.sql
Labels: 멘토 리뷰 요청

#50 [추재호-team C] Assignment3 : Express - API게시글등록하기
  teamC/choojaeho/.env.sample
  teamC/choojaeho/.gitignore
  teamC/choojaeho/app.js
  teamC/choojaeho/db/migrations/20220902080259_create_users.sql
  teamC/choojaeho/db/migrations/20220902080311_create_posts.sql
  teamC/choojaeho/db/migrations/20220902080321_create_likes.sql
  teamC/choojaeho/db/migrations/20220903104010_modify_posts.sql
  teamC/choojaeho/ddd.js
  teamC/choojaeho/package-lock.json
  teamC/choojaeho/package.json
Labels: 수정 요청

#36 [추재호 - team C] Assingment 1: Express API - 초기 환경 세팅
  teamC/choojaeho/.env.sample
  teamC/choojaeho/.gitignore
  teamC/choojaeho/app.js
  teamC/choojaeho/db/migrations/20220901133600_TABLE.sql
  teamC/choojaeho/package-lock.json
  teamC/choojaeho/package.json
Labels: 수정 요청

#48 [추재호-team C] Assignment2 : Express - API유저회원가입하기
  teamC/choojaeho/.gitignore
  teamC/choojaeho/app.js
  teamC/choojaeho/db/migrations/20220901133600_TABLE.sql
  teamC/choojaeho/db/migrations/20220902080259_create_users.sql
  teamC/choojaeho/db/migrations/20220902080311_create_posts.sql
  teamC/choojaeho/db/migrations/20220902080321_create_likes.sql
  teamC/choojaeho/package-lock.json
  teamC/choojaeho/package.json
Labels: 멘토 리뷰 요청

#57 [배규남-teamA] Assignment 3: Express API - CRUD
  teamA/kyunam/.env.sample
  teamA/kyunam/.gitignore
  teamA/kyunam/app.js
  teamA/kyunam/db/migrations/20220904173425_users_table.sql
  teamA/kyunam/db/migrations/20220904173433_posts_table.sql
  teamA/kyunam/db/migrations/20220904173443_likes_table.sql
  teamA/kyunam/package-lock.json
  teamA/kyunam/package.json
Labels: 완료

#55 [배규남-teamA] Assignment 1: Express API - 초기 환경 세팅
  teamA/kyunam/.env.sample
  teamA/kyunam/.gitignore
  teamA/kyunam/app.js
  teamA/kyunam/package-lock.json
  teamA/kyunam/package.json
Labels: 수정 요청

#63 [김성식-teamC] Assignment 1 : Project Layered pattern 적용
  teamC/sungsik/app.js
  teamC/sungsik/controllers/likesController.js
  teamC/sungsik/controllers/postController.js
  teamC/sungsik/controllers/userController.js
  teamC/sungsik/db/migrations/20220902043124_users.sql
  teamC/sungsik/errorHandler/asyncWrap.js
  teamC/sungsik/models/data-source.js
  teamC/sungsik/models/likesDao.js
  teamC/sungsik/models/postDao.js
  teamC/sungsik/models/userDao.js
  teamC/sungsik/routes/index.js
  teamC/sungsik/routes/likesRouter.js
  teamC/sungsik/routes/postRouter.js
  teamC/sungsik/routes/userRouter.js
  teamC/sungsik/services/likesService.js
  teamC/sungsik/services/postService.js
  teamC/sungsik/services/userService.js
Labels: 멘토 리뷰 요청

#66 [정다영-teamC] Assignment 1 : Project Layered pattern 적용
  teamC/dayoung/app.js
  teamC/dayoung/controllers/postController.js
  teamC/dayoung/controllers/userController.js
  teamC/dayoung/models/DataSource.js
  teamC/dayoung/models/postDao.js
  teamC/dayoung/models/userDao.js
  teamC/dayoung/package-lock.json
  teamC/dayoung/package.json
  teamC/dayoung/routes/index.js
  teamC/dayoung/routes/postRouter.js
  teamC/dayoung/routes/userRouter.js
  teamC/dayoung/services/postService.js
  teamC/dayoung/services/userService.js
Labels: 완료

#60 [김응수-teamB] Assignment 1 : Project Layered pattern 적용
  teamB/eungSooKim/app.js
  teamB/eungSooKim/controllers/likeControllers.js
  teamB/eungSooKim/controllers/postControllers.js
  teamB/eungSooKim/controllers/userControllers.js
  teamB/eungSooKim/db/migrations/20220831110804_create_users.sql
  teamB/eungSooKim/db/migrations/20220831111054_create_likes.sql
  teamB/eungSooKim/db/migrations/20220831111107_create_comments.sql
  teamB/eungSooKim/db/migrations/20220903071551_modify_likes.sql
  teamB/eungSooKim/models/likeDao.js
  teamB/eungSooKim/models/postDao.js
  teamB/eungSooKim/models/userDao.js
  teamB/eungSooKim/package-lock.json
  teamB/eungSooKim/package.json
  teamB/eungSooKim/routers/index.js
  teamB/eungSooKim/routers/likeRouter.js
  teamB/eungSooKim/routers/postRouter.js
  teamB/eungSooKim/routers/userRouter.js
  teamB/eungSooKim/services/likeService.js
  teamB/eungSooKim/services/postService.js
  teamB/eungSooKim/services/userService.js
Labels: 완료

#64 [장기석-teamA] Assignment 3 : 로그인 한 사용자만 게시글 등록하기
  teamA/gisuk/.env.sample
  teamA/gisuk/app.js
  teamA/gisuk/controllers/index.js
  teamA/gisuk/controllers/likeController.js
  teamA/gisuk/controllers/postController.js
  teamA/gisuk/controllers/userController.js
  teamA/gisuk/db/migrations/20220831012404_create_user_table.sql
  teamA/gisuk/db/migrations/20220906033556_modify_user_table.sql
  teamA/gisuk/db/migrations/20220906033651_modify_like_table.sql
  teamA/gisuk/middleware/auth.js
  teamA/gisuk/models/likeDao.js
  teamA/gisuk/models/postDao.js
  teamA/gisuk/models/userDao.js
  teamA/gisuk/orm.js
  teamA/gisuk/package-lock.json
  teamA/gisuk/package.json
  teamA/gisuk/routes/index.js
  teamA/gisuk/routes/likeRouter.js
  teamA/gisuk/routes/postRouter.js
  teamA/gisuk/routes/userRouter.js
  teamA/gisuk/services/likeService.js
  teamA/gisuk/services/postService.js
  teamA/gisuk/services/userService.js
Labels: 멘토 리뷰 요청
